apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-processed
spec:
  selector:
    matchLabels:
      app: task-processed
  template:
    metadata:
      labels:
        app: task-processed
    spec:
      containers:
      - name: task-processed
        image: weiqing123/taskprocessor2
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: task-processed
spec:
  type: NodePort
  selector:
    app: task-processed
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32506
