apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskprocess2
spec:
  selector:
    matchLabels:
      app: taskprocess2
  template:
    metadata:
      labels:
        app: taskprocess2
    spec:
      containers:
      - name: taskprocess2
        image: weiqing123/task2
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: taskprocess2
spec:
  type: NodePort
  selector:
    app: taskprocess2
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32505
